/**
 * DORA handbook – English edition, part 2 (chapters 7, 8 and 10–15).
 *
 * Translation of the corresponding sections in lib/content/dora-handbook.ts.
 * Slugs, group IDs, figure numbers and cockpit links are identical to the
 * German source; [[term]] markers reference the canonical keys of the
 * English glossary.
 */

import type { HandbookSection } from "@/lib/content/dora-handbook";

export const HANDBOOK_SECTIONS_EN_PART2: HandbookSection[] = [
  // ─────────────── Part C – Integration, incident reporting & testing ───────────────
  {
    slug: "integration-isms-bcms",
    chapter: "Ch. 7",
    title: "Integrating the ISMS, BCMS and data protection",
    summary:
      "The sweet spot of integration in incident handling and the parallel reporting obligations under DORA, NIS-2 and the GDPR.",
    groupId: "integration",
    figures: [6, 7],
    cockpitLinks: [
      { label: "Incidents & reporting deadlines", href: "/dora/incidents" },
      { label: "Playbooks", href: "/playbooks" },
    ],
    blocks: [
      {
        kind: "p",
        text: "DORA does not demand a complete reinvention of the wheel. Rather, the regulation forces institutions to deeply integrate their historically grown and often separately operated management systems:",
      },
      {
        kind: "list",
        items: [
          "ISMS under ISO/IEC 27001:2022 – focused on safeguarding the protection objectives; provides the preventive controls and day-to-day operational security management.",
          "BCMS under ISO 22301:2019 – focused on maintaining critical business processes in a crisis; in Chapter II, DORA explicitly requires existing and tested continuity and recovery plans for ICT systems.",
          "Data protection under the GDPR – focused on protecting personal data; an ICT incident very often constitutes a personal data breach at the same time.",
        ],
      },
      { kind: "h3", text: "The sweet spot of integration" },
      {
        kind: "p",
        text: "The three systems overlap massively in incident handling and third-party risk. When a service provider is compromised, three strands of obligations must start in parallel and without loss of time.",
      },
      { kind: "figure", num: 6 },
      {
        kind: "p",
        text: "Take a ransomware attack at a service provider as an example: the tool orchestrates the parallel response. The CISO classifies the incident under Art. 18 and reports it under DORA to the financial supervisory authority. At the same time, the system triggers the continuity plans for the BCM officer to keep operations running without the provider. In parallel, it checks the asset register for affected personal data and, where necessary, alerts the data protection officer.",
      },
      { kind: "h3", text: "Parallel reporting obligations and deadlines" },
      {
        kind: "p",
        text: "The deadline regimes of the three frameworks run from the same starting point – the moment of becoming aware – but follow different logics. The DORA initial report is tied to the classification as major, yet has an absolute cap of 24 hours from awareness. The NIS-2 early warning is tied directly to awareness.",
      },
      { kind: "figure", num: 7 },
      {
        kind: "table",
        title: "Table 8: Reporting deadlines in direct comparison",
        head: ["Reporting stage", "DORA (Art. 19, RTS 2025/301)", "NIS-2 / amended BSIG", "GDPR"],
        rows: [
          [
            "Initial report / early warning",
            "4 hours after classification as major, at the latest 24 hours after becoming aware",
            "24 hours after becoming aware",
            "–",
          ],
          [
            "Intermediate report / notification",
            "72 hours after the initial report; without undue delay once regular operations are restored",
            "72 hours after becoming aware",
            "72 hours after becoming aware (Art. 33 GDPR)",
          ],
          [
            "Final report",
            "1 month after the last intermediate report",
            "1 month after the notification",
            "–",
          ],
          [
            "Notification of affected parties",
            "Without undue delay where clients' financial interests are affected (Art. 19(3))",
            "Informing recipients in case of significant impact (Section 35 BSIG)",
            "Without undue delay in case of high risk (Art. 34 GDPR)",
          ],
          [
            "Reporting channel",
            "BaFin (the German Federal Financial Supervisory Authority), reporting and publication portal (MVP)",
            "Reporting portal of the BSI (German Federal Office for Information Security)",
            "Competent data protection supervisory authority",
          ],
          [
            "Form",
            "Harmonised templates under Implementing Regulation (EU) 2025/302",
            "National forms of the BSI (German Federal Office for Information Security)",
            "State-specific forms",
          ],
        ],
      },
      {
        kind: "callout",
        tone: "warn",
        title: "Common implementation error",
        text: "Many concepts set the DORA initial report at 24 hours and thereby equate it with the NIS-2 early warning. That is incorrect: what counts is four hours from classification as major, and the classification itself must be performed quickly enough to stay within the absolute limit of 24 hours from awareness. Anyone who delays the classification breaches the deadline despite formally meeting the 24 hours.",
      },
    ],
  },
  {
    slug: "resilienz-testing",
    chapter: "Ch. 8",
    title: "Resilience testing and TLPT",
    summary:
      "The testing programme under Art. 24/25 and threat-led penetration testing (TLPT) under Art. 26/27 with its three-year cycle.",
    groupId: "integration",
    figures: [8],
    cockpitLinks: [
      { label: "Control library", href: "/controls" },
      { label: "Catalogue: Chapter IV", href: "/dora/requirements?chapter=K4" },
    ],
    blocks: [
      { kind: "h3", text: "Testing programme under Art. 24 and 25" },
      {
        kind: "p",
        text: "Art. 24 requires a sound and comprehensive testing programme as an integral part of the risk management framework. The approach is risk-based; tests must be carried out by independent parties, and identified vulnerabilities must be remediated fully and on time.",
      },
      {
        kind: "p",
        text: "Art. 25 specifies the types of tests. All systems used to support [[critical or important functions]] must be tested at least annually. The spectrum ranges from vulnerability scans and open-source software analyses through source code reviews, scenario-based and performance tests to end-to-end and penetration tests. Evidence must be maintained per test type and per system.",
      },
      { kind: "h3", text: "The TLPT process under Art. 26 and 27" },
      {
        kind: "p",
        text: "Threat-led penetration tests ([[TLPT]]) are DORA's most demanding form of testing. They are not required of all financial entities, but of those designated by the competent authority based on their significance for the financial sector, financial stability and their ICT risk profile. The cycle is at least three years.",
      },
      { kind: "figure", num: 8 },
      {
        kind: "p",
        text: "Two points are regularly underestimated in practice: first, the scope must be validated by the competent authority before testing begins; it mandatorily includes outsourced services as well. Second, the tester requirements of Art. 27 are strict – significant credit institutions may only use external testers, while other entities must have at least every third test performed externally.",
      },
      {
        kind: "p",
        text: "Delegated Regulation (EU) 2025/1190 specifies the methodology, the phase model ([[TIBER-EU]]) and the requirements for the parties involved. The attestation of proper conduct issued by the authority enables mutual recognition throughout the Union and must be archived in an audit-proof manner.",
      },
    ],
  },

  // ─────────────────────── Part D – Methodology & governance ───────────────────────
  {
    slug: "crosswalk",
    chapter: "Ch. 10",
    title: "Crosswalk to ISO 27001, ISO 22301 and NIS-2",
    summary:
      "Methodology of the standards mapping: reuse existing controls, avoid duplicate work – a mapping, not an equivalence.",
    groupId: "steuerung",
    figures: [],
    cockpitLinks: [
      { label: "Catalogue with crosswalk per requirement", href: "/dora/requirements" },
      { label: "Compliance mapping", href: "/compliance" },
    ],
    blocks: [
      {
        kind: "p",
        text: "For each DORA requirement, the crosswalk identifies the substantively corresponding requirements of the established management system standards and of the NIS-2 implementation in the BSIG. It serves two purposes: avoiding duplicate work where certifications already exist, and demonstrating to auditors that existing controls are deliberately reused.",
      },
      {
        kind: "callout",
        tone: "info",
        title: "A mapping, not an equivalence",
        text: "A match means that the existing control provides a solid starting point – not that the DORA requirement is thereby already fulfilled. Where DORA goes beyond the standard, the additional effort must be reflected in the maturity assessment (Ch. 11).",
      },
      {
        kind: "p",
        text: "A dash means that no meaningful correspondence exists. This is regularly the case for the financial-sector-specific requirements – for instance the [[register of information]], the [[TLPT]] requirements and the oversight framework for critical third-party providers ([[CTPP]]).",
      },
      {
        kind: "p",
        text: "The complete crosswalk tables (Tables 16–20 of the source document, all 133 requirements) are implemented database-driven in the cockpit: each requirement's detail page in the requirements catalogue shows the mapping to ISO/IEC 27001:2022, ISO 22301:2019, NIS-2/amended BSIG and the relevant RTS/ITS.",
      },
      {
        kind: "table",
        title: "Reading sample: crosswalk excerpt from Chapter II",
        head: [
          "DORA ID",
          "ISO/IEC 27001:2022",
          "ISO 22301:2019",
          "NIS-2 / amended BSIG",
          "RTS / ITS",
        ],
        rows: [
          [
            "DORA-K2-001",
            "5.1, 5.3, A.5.1, A.5.2",
            "5.1, 5.3",
            "Section 30(1), Section 38 BSIG",
            "Del. Reg. 2024/1774",
          ],
          [
            "DORA-K2-004",
            "6.1.2, 6.1.3",
            "8.2.2",
            "Section 30(2) BSIG",
            "Del. Reg. 2024/1774 Art. 3",
          ],
          [
            "DORA-K2-007",
            "A.5.19, A.5.20",
            "8.1",
            "Section 30(2) no. 4 BSIG",
            "Del. Reg. 2024/1773",
          ],
          ["DORA-K6-001", "A.5.6, A.5.7", "–", "Section 34 BSIG", "–"],
        ],
      },
    ],
  },
  {
    slug: "reifegrad-scoring",
    chapter: "Ch. 11",
    title: "Maturity and scoring model",
    summary:
      "The six-level maturity scale with evidence requirements, the calculation formulas up to the DORA Resilience Index and the traffic-light logic.",
    groupId: "steuerung",
    figures: [9],
    cockpitLinks: [
      { label: "DORA dashboard", href: "/dora" },
      { label: "Assess requirements", href: "/dora/requirements" },
    ],
    blocks: [
      { kind: "h3", text: "Maturity scale" },
      {
        kind: "p",
        text: "Each requirement is assessed on a six-level scale. What counts is not the intention but the demonstrable state as of the reference date. Without a linked, valid piece of evidence, the [[maturity level]] is capped at level 2 at most ([[evidence lock]]) – regardless of the business unit's self-assessment.",
      },
      {
        kind: "table",
        title: "Table 21: Maturity scale with evidence requirements",
        head: ["Level", "Designation", "Definition", "Required evidence"],
        rows: [
          [
            "0",
            "Non-existent",
            "The requirement is not addressed. Neither policies nor activities exist.",
            "No evidence",
          ],
          [
            "1",
            "Initial / ad hoc",
            "The requirement is fulfilled on an ad-hoc, person-dependent basis. No documented policy.",
            "Individual pieces of evidence without a systematic approach",
          ],
          [
            "2",
            "Repeatable",
            "Activities are performed repeatedly but are not fully documented or not applied across the board.",
            "Partial evidence, incomplete documentation",
          ],
          [
            "3",
            "Defined",
            "The requirement is governed by documented, approved and communicated policy and is applied across the board.",
            "Approved policy plus evidence of application",
          ],
          [
            "4",
            "Managed",
            "Implementation is measured through metrics, reviewed regularly and corrected when deviations occur.",
            "Metrics, review minutes, deviation handling",
          ],
          [
            "5",
            "Optimised",
            "Implementation is continuously improved; lessons from tests, incidents and the threat landscape feed in systematically.",
            "Evidence of improvement across several cycles",
          ],
        ],
      },
      { kind: "h3", text: "Calculation logic" },
      {
        kind: "p",
        text: "The chapter score is the quotient of the sum of weighted maturity levels and the sum of the maximum achievable weighted maturity levels. The overall index ([[DORA Resilience Index]]) is the mean weighted by chapter weights. Above both levels sits the [[knockout]] override.",
      },
      { kind: "figure", num: 9 },
      {
        kind: "table",
        title: "Table 22: Score calculation formulas",
        head: ["Quantity", "Calculation"],
        rows: [
          ["Weight per requirement", "MUST = 3, SHOULD = 2, MAY = 1"],
          ["Score per requirement", "Maturity level (0 to 5) × weight"],
          ["Maximum score per requirement", "5 × weight"],
          [
            "Chapter score in percent",
            "Sum of all requirement scores of the chapter ÷ sum of all maximum scores of the chapter × 100",
          ],
          ["DORA Resilience Index", "Sum (chapter score × chapter weight) ÷ 100"],
          [
            "Knockout override",
            "If the chapter contains at least one requirement flagged as KO with a maturity level < 3, the chapter status is set to RED – regardless of the calculated score.",
          ],
          [
            "Evidence lock",
            "If a valid, linked piece of evidence is missing, the system caps the maturity level at 2.",
          ],
        ],
      },
      { kind: "h3", text: "Traffic-light logic" },
      {
        kind: "table",
        title: "Table 23: Traffic-light logic at chapter and overall level",
        head: ["Status", "Condition", "Consequence"],
        rows: [
          [
            "GREEN",
            "Score ≥ 85 % and no open knockout and no overdue action of critical severity.",
            "Regular operations; routine review on a quarterly cycle.",
          ],
          [
            "YELLOW",
            "Score between 60 and 84 % or actions being processed within their deadlines.",
            "Action plan with deadlines; monthly follow-up by the control function.",
          ],
          [
            "RED",
            "Score below 60 % or at least one open knockout.",
            "Immediate escalation to the management body; consideration of suspending affected functions.",
          ],
        ],
      },
      {
        kind: "callout",
        tone: "info",
        title: "Implemented in the cockpit",
        text: "The cockpit computes exactly this logic live: lib/domain/dora-scoring.ts implements weights, evidence lock, chapter score, index and knockout override deterministically – every metric in the dashboard is thus traceable down to the individual requirement.",
      },
    ],
  },
  {
    slug: "findings-capa",
    chapter: "Ch. 12",
    title: "Findings and action management",
    summary:
      "Five sources of findings, the CAPA process with effectiveness checks and the severity levels with deadlines and escalation tiers.",
    groupId: "steuerung",
    figures: [10],
    cockpitLinks: [
      { label: "DORA findings", href: "/dora/findings" },
      { label: "Actions (CAPA)", href: "/actions" },
    ],
    blocks: [
      {
        kind: "p",
        text: "Findings arise from five sources: the self-assessment of the catalogue, the resilience tests including TLPT, the follow-up of incidents, the assessment of service providers, and internal and external audits. All sources feed into a single register so that actions are not treated differently depending on their source.",
      },
      { kind: "h3", text: "Process flow" },
      { kind: "figure", num: 10 },
      {
        kind: "p",
        text: "The decisive control point comes at the end: a finding may only be closed once the effectiveness of the action has been demonstrated against the predefined [[effectiveness criterion]]. Only then is the maturity level of the associated requirement reassessed. This sequence prevents [[CAPA]] actions from being formally closed without eliminating the root cause.",
      },
      { kind: "h3", text: "Severity levels, deadlines and escalation" },
      {
        kind: "table",
        title: "Table 24: Severity levels, remediation deadlines and escalation tiers",
        head: [
          "Severity",
          "Definition",
          "Response deadline",
          "Remediation deadline",
          "Escalation to",
        ],
        rows: [
          [
            "Critical",
            "Knockout-relevant MUST requirement with a maturity level below 3, or an immediate threat to a critical function.",
            "Immediately",
            "10 working days",
            "Management body",
          ],
          [
            "High",
            "MUST requirement with a maturity level below 3 without an immediate CIF threat, or a material evidence deficiency.",
            "5 working days",
            "30 working days",
            "CISO",
          ],
          [
            "Medium",
            "SHOULD requirement not fulfilled, or MUST requirement at maturity level 3 with identifiable need for improvement.",
            "10 working days",
            "90 working days",
            "Head of business unit",
          ],
          [
            "Low",
            "Formal or documentation deficiencies without impact on the effectiveness of the control.",
            "20 working days",
            "180 working days",
            "Process owner",
          ],
        ],
      },
      {
        kind: "p",
        text: "If the remediation deadline is exceeded, an automatic escalation to the next-higher tier occurs. Overdue actions of critical severity are reported separately in the dashboard's executive overview and form part of every report to the [[management body]].",
      },
    ],
  },
  {
    slug: "kennzahlen",
    chapter: "Ch. 13",
    title: "Metrics system – KPIs and KRIs",
    summary:
      "The metrics tree from the DORA Resilience Index down to the individual metric, and the complete KPI/KRI catalogue with target values.",
    groupId: "steuerung",
    figures: [11],
    cockpitLinks: [
      { label: "DORA dashboard (KPI list)", href: "/dora" },
      { label: "Reports", href: "/reports" },
    ],
    blocks: [
      {
        kind: "p",
        text: "The metrics system distinguishes between key performance indicators (KPIs), which measure the degree of implementation, and key risk indicators (KRIs), which point to threats. Both are anchored per chapter and aggregate into the [[DORA Resilience Index]].",
      },
      { kind: "figure", num: 11 },
      { kind: "h3", text: "Metrics catalogue" },
      {
        kind: "p",
        text: "The following table defines, for each metric, the calculation, the target value, the collection frequency and the data source. The definitions can be translated directly into application queries – a selection of them is calculated live in the cockpit's DORA dashboard.",
      },
      {
        kind: "table",
        title: "Table 25: Catalogue of performance and risk indicators",
        head: ["ID", "Designation", "Level", "Calculation", "Target value", "Frequency"],
        rows: [
          [
            "KPI-K2-01",
            "Coverage of critical functions with a BIA",
            "Chapter II",
            "CIFs with an approved BIA / number of CIFs",
            "100 %",
            "Quarterly",
          ],
          [
            "KPI-K2-02",
            "Assets with a complete 5D protection-needs assessment",
            "Chapter II",
            "Assets with all five dimensions / CIF-relevant assets",
            "100 %",
            "Quarterly",
          ],
          [
            "KPI-K2-03",
            "Success rate of BCP and DRP tests",
            "Chapter II",
            "Passed tests / planned tests in the cycle",
            "≥ 95 %",
            "Semi-annually",
          ],
          [
            "KRI-K2-04",
            "Risks above the risk appetite",
            "Chapter II",
            "Open risks above the tolerance threshold",
            "0",
            "Monthly",
          ],
          [
            "KRI-K2-05",
            "Share of legacy systems in CIF chains",
            "Chapter II",
            "Legacy assets in CIF chains / total CIF assets",
            "≤ 10 %",
            "Semi-annually",
          ],
          [
            "KPI-K3-01",
            "Reporting deadline adherence",
            "Chapter III",
            "Reports submitted on time / reportable incidents",
            "100 %",
            "Monthly",
          ],
          [
            "KPI-K3-02",
            "Mean Time to Detect (MTTD)",
            "Chapter III",
            "Mean time from occurrence to detection",
            "≤ 1 hour",
            "Monthly",
          ],
          [
            "KPI-K3-03",
            "Mean Time to Restore (MTTR)",
            "Chapter III",
            "Mean time from detection to restoration",
            "≤ RTO of the affected CIF",
            "Monthly",
          ],
          [
            "KPI-K3-04",
            "Lessons learned transferred",
            "Chapter III",
            "Incidents with an entry in the risk register / major incidents",
            "100 %",
            "Quarterly",
          ],
          [
            "KRI-K3-05",
            "Major incidents per quarter",
            "Chapter III",
            "Number of incidents classified as major",
            "Trend monitoring",
            "Quarterly",
          ],
          [
            "KPI-K4-01",
            "Test plan fulfilment",
            "Chapter IV",
            "Tests performed / tests planned in the annual cycle",
            "≥ 95 %",
            "Quarterly",
          ],
          [
            "KPI-K4-02",
            "TLPT cycle adherence",
            "Chapter IV",
            "Time since the last completed TLPT",
            "≤ 36 months",
            "Semi-annually",
          ],
          [
            "KPI-K4-03",
            "Retest rate after remediation",
            "Chapter IV",
            "Retested findings / remediated findings",
            "100 %",
            "Quarterly",
          ],
          [
            "KRI-K4-04",
            "Open test findings by severity",
            "Chapter IV",
            "Open findings per severity, weighted by age",
            "0 critical",
            "Monthly",
          ],
          [
            "KPI-K5-01",
            "Completeness of the register of information",
            "Chapter V",
            "Contracts with a complete data set / total contracts",
            "100 %",
            "Monthly",
          ],
          [
            "KPI-K5-02",
            "Contractual clause conformity under Art. 30",
            "Chapter V",
            "Contracts with all mandatory clauses / CIF contracts",
            "100 %",
            "Quarterly",
          ],
          [
            "KPI-K5-03",
            "Tested exit strategies",
            "Chapter V",
            "CIF providers with a tested exit plan / CIF providers",
            "100 %",
            "Semi-annually",
          ],
          [
            "KRI-K5-04",
            "Concentration risk per provider",
            "Chapter V",
            "Number of CIFs depending on a single provider",
            "≤ 2 per provider",
            "Quarterly",
          ],
          [
            "KRI-K5-05",
            "Non-substitutable providers",
            "Chapter V",
            "CIF providers without an available alternative",
            "0",
            "Semi-annually",
          ],
          [
            "KPI-K6-01",
            "Threat intelligence evaluation rate",
            "Chapter VI",
            "Evaluated alerts / received alerts",
            "100 %",
            "Monthly",
          ],
          [
            "KPI-K6-02",
            "Time to Assess after an external alert",
            "Chapter VI",
            "Mean time from alert to completed register reconciliation",
            "≤ 24 hours",
            "Monthly",
          ],
          [
            "KPI-GOV-01",
            "DORA Resilience Index",
            "Overall",
            "Weighted mean of the chapter scores with knockout override",
            "≥ 85 %",
            "Quarterly",
          ],
          [
            "KRI-GOV-02",
            "Open knockouts",
            "Overall",
            "MUST requirements with a maturity level below 3",
            "0",
            "Monthly",
          ],
          ["KRI-GOV-03", "Overdue CAPAs", "Overall", "Actions past their due date", "0", "Monthly"],
        ],
      },
    ],
  },
  {
    slug: "governance-raci",
    chapter: "Ch. 14",
    title: "Governance and responsibilities",
    summary:
      "The three-lines-of-defense model and the RACI matrix across DORA Chapters II to VI – including the incompatibility rule for internal audit.",
    groupId: "steuerung",
    figures: [12],
    cockpitLinks: [
      { label: "Administration (roles)", href: "/admin" },
      { label: "Audit trail", href: "/audit" },
    ],
    blocks: [
      {
        kind: "p",
        text: "DORA requires a clear separation of execution, control and audit. Art. 6(4) demands an independent control function for ICT risk, and Art. 6(6) the regular review of the framework by internal audit. The assignment follows the model of the [[three lines of defense]].",
      },
      { kind: "figure", num: 12 },
      { kind: "h3", text: "RACI overview per DORA chapter" },
      {
        kind: "p",
        text: "The matrix assigns each role its involvement per chapter. A stands for ultimate accountability, R for responsibility for execution, C for mandatory consultation and I for information.",
      },
      {
        kind: "table",
        title: "Table 26: RACI matrix across DORA Chapters II to VI",
        head: ["Role", "II", "III", "IV", "V", "VI", "Focus of the role"],
        rows: [
          [
            "Management body / board",
            "A",
            "I",
            "I",
            "A",
            "I",
            "Approves the strategy, risk appetite and outsourcing policy; bears ultimate accountability under Art. 5(2).",
          ],
          [
            "CISO / ICT risk management",
            "R",
            "R",
            "R",
            "C",
            "R",
            "Runs the risk management framework, is responsible for classification and reporting, steers the testing programme.",
          ],
          [
            "Third-party risk management",
            "C",
            "C",
            "C",
            "R",
            "C",
            "Maintains the register of information and provider assessments, manages concentration risk and exit strategies.",
          ],
          [
            "BCM officer",
            "R",
            "C",
            "C",
            "C",
            "I",
            "Responsible for the BIA, BCP and DRP as well as setting RTO/RPO and their tests.",
          ],
          [
            "IT operations and architecture",
            "R",
            "C",
            "R",
            "C",
            "I",
            "Implements technical controls, maintains the CMDB, patch and change management.",
          ],
          [
            "Security Operations (SOC)",
            "C",
            "R",
            "C",
            "I",
            "R",
            "Detection and first response, forensics, evaluation of threat intelligence.",
          ],
          [
            "Business units / CIF owners",
            "R",
            "C",
            "C",
            "C",
            "I",
            "Process ownership, BIA input, protection-needs determination.",
          ],
          [
            "Procurement and legal",
            "I",
            "I",
            "I",
            "R",
            "I",
            "Contract negotiation and ensuring the mandatory clauses under Art. 30.",
          ],
          [
            "Compliance",
            "C",
            "C",
            "C",
            "C",
            "C",
            "Regulatory interpretation, communication with supervisors, delineation of parallel reporting obligations.",
          ],
          [
            "Data protection officer",
            "I",
            "C",
            "I",
            "C",
            "I",
            "Assessment of data protection reporting obligations and interface to the GDPR.",
          ],
          [
            "Internal audit",
            "I",
            "I",
            "I",
            "I",
            "I",
            "Independent review of the framework under Art. 6(6); no operational mandate.",
          ],
        ],
      },
      {
        kind: "callout",
        tone: "danger",
        title: "Incompatibility",
        text: "Internal audit must not be assigned R or A in any chapter. A dual role combining operational implementation and independent review violates Art. 6(4) and (6) and is a regular ground for objections in supervisory examinations.",
      },
    ],
  },

  // ─────────────────── Part E – Architecture & implementation ───────────────────
  {
    slug: "architektur-dashboard",
    chapter: "Ch. 15",
    title: "GRC architecture and dashboard specification",
    summary:
      "The four-layer target architecture, the executive overview, the view map, the data model and the application's interfaces.",
    groupId: "architektur",
    figures: [13, 14, 15, 16],
    cockpitLinks: [
      { label: "DORA dashboard (implementation of Fig. 14)", href: "/dora" },
      { label: "Incidents & reporting deadline monitor", href: "/dora/incidents" },
      { label: "Reports & exports", href: "/reports" },
    ],
    blocks: [
      {
        kind: "p",
        text: "Documents and simple ticketing systems are not sufficient to represent the DORA requirements. The number of individual requirements, the density of links between requirement, asset, function, provider and incident, and the short [[reporting deadlines]] necessitate a structured application with a single authoritative data base.",
      },
      { kind: "h3", text: "Target architecture" },
      {
        kind: "p",
        text: "The architecture is built in four layers: the foundation is the asset inventory as the single source of truth. Above it sits the business context with the critical and important functions, which passes the business impact down to the operational modules. The third layer comprises the DORA modules, the fourth the management and supervisory reporting.",
      },
      { kind: "figure", num: 13 },
      {
        kind: "p",
        text: "The core of the architecture is the linkage: every risk, every incident and every provider must be connected to a concrete ICT asset and, through it, to a critical function. Only then can the impact of a component's failure on the overall business be calculated automatically – and only then is classifying an incident within the four-hour deadline feasible at all.",
      },
      { kind: "h3", text: "Dashboard – executive overview" },
      {
        kind: "p",
        text: "The target view for the [[management body]] is the binding design template for the implementation and contains all elements required for reporting under Art. 5(2). The values shown are example values.",
      },
      { kind: "figure", num: 14 },
      {
        kind: "list",
        items: [
          'The "Open knockouts" tile ranks on par with the overall index. It prevents a good average from concealing a hard compliance gap.',
          "The chapter traffic light is overridden by knockouts. In the example, Chapter V is RED despite 67 percent, because exit strategies for providers of critical functions are missing.",
          "The heatmap connects the chapter view with the view of critical functions and makes it possible to answer which business process is concretely at risk.",
          "The reporting deadline monitor shows the remaining time per ongoing incident and automatically checks the three parallel strands of obligations under DORA, NIS-2 and the GDPR.",
        ],
      },
      { kind: "h3", text: "View map" },
      {
        kind: "p",
        text: "The application is organised into seven workspaces, each assigned to a target audience and a DORA chapter. The separation is deliberate: the management body receives a condensed view, while the business units work within their respective domain.",
      },
      { kind: "figure", num: 15 },
      { kind: "h3", text: "Data model" },
      {
        kind: "p",
        text: "The entity-relationship model represents the business objects and their relationships. It is designed to map directly onto relational tables – in the cockpit it is implemented in prisma/schema.prisma (DoraChapter, DoraRequirement, DoraAssessment, DoraFinding, Incident, IncidentReport, Evidence, among others). Cardinalities are shown in crow's-foot notation.",
      },
      { kind: "figure", num: 16 },
      { kind: "h3", text: "Calculation and status logic" },
      {
        kind: "list",
        items: [
          "The maturity level of a requirement is capped at 2 as long as no valid piece of evidence is linked. Evidence is considered valid if its validity date has not passed and the review flag is set.",
          "The chapter score is recalculated on every assessment change and historised with a reference date. Historical states must not be overwritten.",
          "The knockout check runs after every assessment change and after every status change of a finding. It sets the chapter status without altering the score.",
          "When an incident is recorded, the system calculates the due dates from the time of awareness and classification and starts the deadline monitoring.",
          "The reporting deadline monitor checks, per incident, the applicability of the obligation strands under DORA, the BSIG and the GDPR, and documents the assessment decision even when no reporting obligation applies.",
          "Every change to assessments, findings, actions and evidence is recorded in the audit log with old value, new value, user and timestamp. The audit log is append-only.",
          "The concentration risk indicator counts, per provider, the number of dependent critical functions and specifically flags providers without a documented alternative.",
        ],
      },
      { kind: "h3", text: "Role and authorisation concept" },
      {
        kind: "table",
        title: "Table 28: Role and authorisation concept of the application",
        head: ["Role", "Catalogue", "Incidents", "Providers", "Register", "Threat intel", "Note"],
        rows: [
          [
            "Management body",
            "Read",
            "Read",
            "Read",
            "Read",
            "Read",
            "Executive overview and management report; no write permissions.",
          ],
          [
            "CISO",
            "Write",
            "Write",
            "Write",
            "Read",
            "Write",
            "Full access to assessments, findings, incidents and approvals.",
          ],
          [
            "TPRM",
            "Read",
            "Read",
            "Write",
            "Write",
            "Read",
            "Full access to providers, contracts and the register of information.",
          ],
          [
            "Business unit / CIF owner",
            "Write (own)",
            "Read",
            "Read",
            "Read",
            "Read",
            "Write permission only for their own assigned requirements.",
          ],
          [
            "SOC",
            "Read",
            "Write",
            "Read",
            "Read",
            "Write",
            "Full access to incidents and threat intelligence.",
          ],
          [
            "Internal audit",
            "Read",
            "Read",
            "Read",
            "Read",
            "Read",
            "Read access to all data including the audit trail; no write permissions.",
          ],
          [
            "Administrator",
            "Manage",
            "Manage",
            "Manage",
            "Manage",
            "Manage",
            "Master data, roles and configuration; no substantive assessments.",
          ],
        ],
      },
      { kind: "h3", text: "Interfaces and data exchange" },
      {
        kind: "table",
        title: "Table 29: Required interfaces",
        head: ["Interface", "Direction", "Purpose and format"],
        rows: [
          [
            "CMDB / asset management",
            "Inbound",
            "Periodic reconciliation of the asset inventory; the reconciliation key is the asset ID. Format JSON or CSV.",
          ],
          [
            "Register of information",
            "Outbound",
            "Generation of the submission file for BaFin (the German Federal Financial Supervisory Authority) in xBRL format under ITS (EU) 2024/2956 or as an Excel template, incl. pre-validation.",
          ],
          [
            "Incident reporting",
            "Outbound",
            "Population of the harmonised reporting forms under Implementing Regulation (EU) 2025/302 for submission via the MVP portal.",
          ],
          [
            "SIEM / security operations",
            "Inbound",
            "Ingestion of classification-relevant incident data to trigger the deadline monitoring.",
          ],
          [
            "Threat intelligence feeds",
            "Inbound",
            "Automated reconciliation of incoming advisories against the asset inventory and the register of information; format STIX or JSON.",
          ],
          [
            "Evidence repository",
            "Bidirectional",
            "Linking of evidence documents with versioning and retention period.",
          ],
          [
            "Management reporting",
            "Outbound",
            "Generation of the evidence package and the management report as a PDF export with data cut-off and checksum.",
          ],
        ],
      },
    ],
  },
];
